### ISSUE TITLE
cassandra-integration-tests  stuck without any output

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/cpp-driver#13]
Running the tests (all except of AuthenticationTests) as:
```
cassandra-integration-tests  --version=2.15.2 --category=CASSANDRA --verbose=ccm --gtest_filter=*-AuthenticationTests*
```

Test runs with relocatable packages using environment variables:
- SCYLLA_VERSION
- SCYLLA_CORE_PACKAGE
- SCYLLA_JAVA_TOOLS_PACKAGE
- SCYLLA_JMX_PACKAGE

The test looks stuck. No output, no errors.

Found that just two tests ran:
```
[jenkins@public-jenkins-builder4-qavpc cpp-driver-matrix]$ ls /jenkins/slave/workspace/scylla-staging/yulia/staging-cpp-driver-matrix-test@2/cpp-driver-scylla/log/AsyncTests
Integration_Cassandra_Close.log  Integration_Cassandra_Simple.log
```

Jenkins job: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-cpp-driver-matrix-test/109/console

**Comment by kbr-** [comment]
@juliayakovlev I can't access the linked jenkins job, seems that it was already deleted.
Did this error reproduce in any recent run?

**Comment by juliayakovlev** [comment]
> @juliayakovlev I can't access the linked jenkins job, seems that it was already deleted.
> Did this error reproduce in any recent run?

Yes, seems it was deleted.
This issue already solved by @jul-stas : #14 .

**Comment by kbr-** [comment]
I wanted to investigate the issue further

**Comment by juliayakovlev** [comment]
> I wanted to investigate the issue further

I run the test with this fix only, so I don't have another run with this problem
