### ISSUE TITLE
Document the Scylla CPP Driver with the Scylla Sphinx Theme

### ISSUE THREAD

**Issue by lauranovich** [scylladb/cpp-driver#15]
Just like the Python and Java Driver, the Scylla Sphinx Theme should be applied to the CPP Driver. 

The Process includes:
1. Following the steps - https://github.com/scylladb/sphinx-scylladb-theme/blob/master/README.rst
2. Testing the output
3. Making sure everything we display is branded Scylla not Datastax
4. Making sure the links are all directed to Scylla
5. Adding multiversion when the next version goes out.

**Comment by tzach** [comment]
@lauranovich can you add the wording, similar to what we did for the Java driver
@dgarcia360 can you send a PR for the doc generation?

**Comment by lauranovich** [comment]
@dgarcia360 this driver is now released, we need to get this done.

**Comment by dgarcia360** [comment]
@tzach @lauranovich https://github.com/scylladb/cpp-driver/issues/15 should generate the docs. The site will be published in https://cpp-driver.docs.scylladb.com/

To autogenerate the [API Reference](https://docs.datastax.com/en/developer/cpp-driver/2.15/api/) documentation I've been testing the extensions [breathe](https://breathe.readthedocs.io/en/latest/) and [exhale](https://exhale.readthedocs.io/en/latest/), but the second is not compatible with multiversion. 

While you make sure everything we display is branded Scylla not Datastax, I'll continue researching for other extensions and alternative solutions to autogenerate the reference docs.

**Comment by jul-stas** [comment]
@dgarcia360 Am I supposed to do the generation?

**Comment by lauranovich** [comment]
@tzach - working on the wording there is a PR currently in place from @jul-stas - I am fixing it.

**Comment by dgarcia360** [comment]
@jul-stas The docs should be built and published automatically with https://github.com/scylladb/cpp-driver/pull/21 . Please merge it once @lauranovich or @tzach review the PR.

**Comment by dgarcia360** [comment]
Added the API Reference autogeneration to https://github.com/scylladb/cpp-driver/pull/21

**Comment by jul-stas** [comment]
We have the Sphinx theme and a separate task for fixing links, so I'm closing this.
