### ISSUE TITLE
About section must be changed

### ISSUE THREAD

**Issue by lauranovich** [scylladb/cpp-driver#18]
On the Repo description where it says about:
![Screenshot from 2021-01-13 19-27-14](https://user-images.githubusercontent.com/36125151/104487126-5ce77600-55d5-11eb-97be-8e37deb7f614.png)

About
[MAINTENANCE ONLY] DataStax C/C++ Driver for Apache Cassandra

We need to change this ASAP as users will now be looking for this driver and it is clearly not maintenance only!

**Comment by jul-stas** [comment]
Done.
