### ISSUE TITLE
SSL timeout with advanced shard-awareness

### ISSUE THREAD

**Issue by jul-stas** [scylladb/cpp-driver#37]
From users slack channel:
```
I'm trying to get the Shard-aware Scylla C++ driver (https://cpp-driver.docs.scylladb.com/master/) working with SSL, but am 
unable to do so. It works successfully only on port 19042. If I change the linker to use cassandra-cpp-driver instead of scylla-cpp-
driver, the SSL connection is successful.I've included my modified code and the log output for all 8 combinations of the two ports, 
SSL enabled/disabled, and both driver types.I'm using scylla-cpp-driver-2.15.2-1 or cassandra-cpp-driver-2.15.3 on Ubuntu 20.04 
Server LTS. Both drivers are compiled from source.
```

[scylla-test-code.txt](https://github.com/scylladb/cpp-driver/files/6755677/scylla-test-code.txt)
[scylla-test-log-output.txt](https://github.com/scylladb/cpp-driver/files/6755675/scylla-test-log-output.txt)

**Comment by ramman3000** [comment]
This problem occurred with the same log messages, regardless of whether port 9142 or 19142 was explicitly chosen, or whether or not "cass_cluster_set_local_port_range(cluster, 50000, 60000);" was specified. I could not make any SSL connections at all using this driver, whether or not advanced shard-awareness was enabled.

The control cassandra-cpp-driver worked in all SSL scenarios (except that you can't compile it with "cass_cluster_set_local_port_range(cluster, 50000, 60000);" for obvious reasons).

**Comment by jul-stas** [comment]
The problem is caused by TLS 1.3. I'll limit the version to 1.2, but as a **very temporary** quickfix you can set:
```
SSL_CTX_set_max_proto_version(ssl_ctx_, TLS1_2_VERSION)
```
in `OpenSslContext()`.

**Comment by ramman3000** [comment]
Using the temporary fix, I am now able to make an SSL connection. In the logs it says "Using optimized driver!!!", but it only opens port 9142, not 19142. Moreover, unless I explicitly set the protocol version...

```
int protocol_version = 3;
cass_cluster_set_protocol_version(cluster, protocol_version);
```

...the connection fails. It attempts to connect to 9142, fails, and then tries to connect to 19042 (**not** 19142), before giving up completely: [scylla-test-log-output3.txt](https://github.com/scylladb/cpp-driver/files/6779912/scylla-test-log-output3.txt).

As before, unless I specify...

```
  int port = 9142;
  cass_cluster_set_port(cluster, port);

```

...it won't make an SSL connection on any port. The only way I can get it to connect to 19142 is if I specify that port manually instead of 9142.

**Comment by jul-stas** [comment]
> 
> 
> Using the temporary fix, I am now able to make an SSL connection. In the logs it says "Using optimized driver!!!", but it only opens port 9142, not 19142. Moreover, unless I explicitly set the protocol version...
> 
> ```
> int protocol_version = 3;
> cass_cluster_set_protocol_version(cluster, protocol_version);
> ```
> 
> ...the connection fails. It attempts to connect to 9142, fails, and then tries to connect to 19042 (**not** 19142), before giving up completely: [scylla-test-log-output3.txt](https://github.com/scylladb/cpp-driver/files/6779912/scylla-test-log-output3.txt).
> 
> As before, unless I specify...
> 
> ```
>   int port = 9142;
>   cass_cluster_set_port(cluster, port);
> ```
> 
> ...it won't make an SSL connection on any port. The only way I can get it to connect to 19142 is if I specify that port manually instead of 9142.

Yes, this is another bug that flew under the radar due to some changes in Scylla (server), esp. how it handles `client_encryption_options`. Now that it's recognized I'm fixing them both in the upcoming PR; please expect a patchlevel bump soon.
