### ISSUE TITLE
Scylla Driver crashes

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/cpp-driver#56]
We are observing core dump in libuv library( libuv-1.10.1) when we use Scylla cpp driver version 2.15.2 .  There are 2 scylla nodes configured with 32 cores each. Number of IO threads is set to 2.  And total number of connections created is 127.  Following is the bt of the coredump,

```
(gdb) bt
#0 heap_remove (less_than=0x1560470 <timer_less_than>, node=0x700ee80, heap=0xe3c0a20) at ./src/heap-inl.h:196
#1 uv_timer_stop (handle=0x700ee18) at src/unix/timer.c:97
#2 0x00000000015608e4 in uv_timer_start (handle=0x700ee18, cb=0x7fb1fcd7c810 <datastax::internal::core::Timer::on_timeout(uv_timer_s*)>, timeout=45000, repeat=0)
at src/unix/timer.c:72
#3 0x00007fb1fcd7c716 in datastax::internal::core::Timer::start (this=this@entry=0xac506d30, loop=0xe3c0818, timeout=<optimized out>, callback=...)
at ./src/timer.cpp:39
#4 0x00007fb1fcccf8c9 in datastax::internal::core::Connection::restart_terminate_timer (this=0xac506c08) at ./src/connection.cpp:342
#5 0x00007fb1fccd0624 in datastax::internal::core::Connection::on_read (this=0xac506c08, buf=0xad784008 "\204", size=6638) at ./src/connection.cpp:235
#6 0x00007fb1fccd0c68 in datastax::internal::core::ConnectionHandler::on_read (this=0xad688ed8, socket=<optimized out>, nread=<optimized out>, buf=0x7fb1e816b560)
at ./src/connection.cpp:75
#7 0x000000000155de6c in uv__read (stream=stream@entry=0xac506610) at src/unix/stream.c:1197
#8 0x000000000155e76c in uv__stream_io (loop=<optimized out>, w=0xac506698, events=1) at src/unix/stream.c:1263
#9 0x0000000001562908 in uv__io_poll (loop=loop@entry=0xe3c0818, timeout=11994) at src/unix/linux-core.c:382
#10 0x0000000001558ad8 in uv_run (loop=0xe3c0818, mode=UV_RUN_DEFAULT) at src/unix/core.c:352
#11 0x00007fb1fcd0da75 in datastax::internal::core::EventLoop::handle_run (this=0xe3c0810) at ./src/event_loop.cpp:168
#12 0x00007fb1f912cea5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007fb1f82279fd in clone () from /lib64/libc.so.6
(gdb)
```
We have added a null check as per the solution suggested in https://github.com/libuv/libuv/issues/1439t, but then it started dumping in heap_insert.

**Comment by ebenzecri** [comment]
@jul-stas If you need anything else, let me know. Thanks!

**Comment by Lorak-mmk** [comment]
Would it be possible to check if problem still exists with current master? It may be this issue: https://github.com/scylladb/cpp-driver/issues/36 which was fixed by this PR: https://github.com/scylladb/cpp-driver/pull/40

**Comment by ebenzecri** [comment]
@Lorak-mmk I'm not sure if a customer wants to compile the driver just for testing. Is there any chance you guys offer a new release for the Release section? It would be easier to offer a ready-to-use package.

**Comment by Lorak-mmk** [comment]
I think it would be better if @jul-stas created a package, I've never done that. In the mean time, you can try with 1 IO thread - if the issue disappears, then this is most likely the issue that I mentioned.

**Comment by jul-stas** [comment]
@ebenzecri Did the new release help?

**Comment by ebenzecri** [comment]
@jul-stas Once I get the feedback I'll let you know

**Comment by ebenzecri** [comment]
No complaints received, so closing this issue. Thanks!
